# Generated by Django 6.0.6 on 2026-06-23 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ai_mode',
            field=models.CharField(choices=[('none', 'No AI'), ('self_hosted', 'Self-Hosted AI'), ('paid', 'Paid AI Model')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='allow_start_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingresponse',
            name='participant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingresponse',
            name='response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingresponse',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='meetingresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.meetingquestion'),
        ),
        migrations.AlterField(
            model_name='meetingresponse',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.UUIDField(db_index=True, unique=True)),
                ('participant_id', models.UUIDField(db_index=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('left', 'Left')], default='joined', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meeting attendances',
            },
        ),
        migrations.AddField(
            model_name='meetingresponse',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='api.meetingattendance'),
        ),
        migrations.CreateModel(
            name='MeetingResponseAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('support_level', models.CharField(blank=True, max_length=50)),
                ('opposition_level', models.CharField(blank=True, max_length=50)),
                ('action_item', models.TextField(blank=True)),
                ('decision_made', models.TextField(blank=True)),
                ('unresolved_question', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai', to='api.meetingresponse')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.meeting')),
            ],
            options={
                'ordering': ['-session_number', '-id'],
            },
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.meetingsession'),
        ),
        migrations.AddField(
            model_name='meetingresponse',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.meetingsession'),
        ),
        migrations.CreateModel(
            name='MeetingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slide_type', models.CharField(choices=[('participant_info', 'Participant information'), ('standard', 'Standard question'), ('issue_card', 'Issue card'), ('political_issue_card', 'Political issue card')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('prompt', models.TextField(blank=True)),
                ('question_format', models.CharField(blank=True, choices=[('text', 'Free text'), ('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice')], default='', max_length=20)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.meeting')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='current_slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.meetingslide'),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='started_from_slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.meetingslide'),
        ),
        migrations.AddField(
            model_name='meetingresponse',
            name='slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.meetingslide'),
        ),
        migrations.CreateModel(
            name='PoliticalClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_issue_bucket', models.CharField(blank=True, max_length=200)),
                ('specific_issue_bucket', models.CharField(blank=True, max_length=200)),
                ('concern_bucket', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='ai', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='political_classifications', to='api.meetingresponse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='meetingsession',
            unique_together={('meeting', 'session_number')},
        ),
        migrations.CreateModel(
            name='ParticipantProfileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_values', to='api.meetingattendance')),
            ],
            options={
                'unique_together': {('attendance', 'field_key')},
            },
        ),
    ]
