# Generated by Django 6.0.6 on 2026-07-11 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_boards_and_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Organization = apps.get_model("api", "Organization")
    OrganizationBoard = apps.get_model("api", "OrganizationBoard")
    PersonalBoard = apps.get_model("api", "PersonalBoard")
    UserProfile = apps.get_model("api", "UserProfile")

    for org in Organization.objects.all():
        OrganizationBoard.objects.get_or_create(organization=org)
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)
        PersonalBoard.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_meetingresponse_importance_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardpost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="boardpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organizationboard",
            name="posting_mode",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members_only", "Members only"),
                    ("restricted", "Restricted (admin posts only)"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PersonalBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="My board", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_board",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalBoardPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="api.personalboard",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(backfill_boards_and_profiles, migrations.RunPython.noop),
    ]
