# Generated by Django 6.0.6 on 2026-08-09 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_political_issue_classification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='geographic_scope',
            field=models.CharField(blank=True, choices=[('international', 'International'), ('national', 'National'), ('state_province', 'State / Province'), ('regional', 'Regional'), ('local', 'Local')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarters_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarters_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organizations', to='api.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='search_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GeographicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('area_type', models.CharField(choices=[('country', 'Country'), ('admin1', 'State / Province / Territory'), ('admin2', 'County / County-equivalent'), ('region', 'Regional area')], max_length=20)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('external_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('name_search', models.CharField(blank=True, db_index=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.geographicarea')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarters_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_headquartered', to='api.geographicarea'),
        ),
        migrations.AddField(
            model_name='organization',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_serving', to='api.geographicarea'),
        ),
        migrations.CreateModel(
            name='OrgCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.orgcategory')),
            ],
            options={
                'verbose_name_plural': 'org categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='api.orgcategory'),
        ),
        migrations.AddIndex(
            model_name='geographicarea',
            index=models.Index(fields=['area_type', 'parent', 'name_search'], name='api_geograp_area_ty_72bf41_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicarea',
            index=models.Index(fields=['country_code', 'area_type'], name='api_geograp_country_4de290_idx'),
        ),
        migrations.AddConstraint(
            model_name='geographicarea',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'slug'), name='uniq_geo_parent_slug'),
        ),
        migrations.AddConstraint(
            model_name='geographicarea',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='uniq_geo_root_slug'),
        ),
        migrations.AddConstraint(
            model_name='orgcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'slug'), name='uniq_orgcategory_parent_slug'),
        ),
        migrations.AddConstraint(
            model_name='orgcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='uniq_orgcategory_root_slug'),
        ),
    ]
