# Generated by Django 6.0.8 on 2026-08-10 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_geographicarea_locality"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_level",
                    models.CharField(
                        choices=[
                            ("FREE", "Organization (Free)"),
                            ("BASIC", "Basic"),
                            ("COMMUNITY", "Community"),
                            ("COMMUNITY_PLUS", "Community Plus"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "billing_source",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("PAYPAL", "PayPal"),
                            ("ACCESS_CODE", "Access code"),
                            ("ADMIN_GRANT", "Administrative grant"),
                            ("ENTERPRISE_CONTRACT", "Enterprise contract"),
                        ],
                        default="FREE",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("PAYMENT_FAILED", "Payment failed"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("paypal_plan_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "paypal_subscription_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "billing_reference",
                    models.CharField(
                        help_text="Opaque CommuniB billing reference (e.g. COMMUNIB-SUB-000184-00001).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="api_organiz_organiz_cf95cb_idx",
                    ),
                    models.Index(
                        fields=["organization", "service_level", "status"],
                        name="api_organiz_organiz_7b0cb6_idx",
                    ),
                ],
            },
        ),
    ]
