# Generated by Django 6.0.8 on 2026-08-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mailbox_inbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='api.mailbox')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to='api.mailbox')),
            ],
            options={
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='api_mailbox_blocker_395c02_idx'), models.Index(fields=['blocked', 'blocker'], name='api_mailbox_blocked_6df84c_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
