# Generated by Django 6.0.8 on 2026-08-11 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def promote_owners(apps, schema_editor):
    Organization = apps.get_model("api", "Organization")
    OrganizationMembership = apps.get_model("api", "OrganizationMembership")
    for org in Organization.objects.all().iterator():
        if OrganizationMembership.objects.filter(organization=org, role="owner").exists():
            continue
        first_admin = (
            OrganizationMembership.objects.filter(organization=org, role="admin")
            .order_by("id")
            .first()
        )
        if first_admin:
            first_admin.role = "owner"
            first_admin.save(update_fields=["role"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_mailbox_block"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="closure_effective_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="restored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restored_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closure_pending", "Closure pending"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="active",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="organizationservice",
            name="cancel_at_period_end",
            field=models.BooleanField(
                default=False,
                help_text="When True, keep ACTIVE paid access until current_period_end, then expire.",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Legacy visibility flag; kept in sync with status (False when closed).",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrganizationAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ownership_transferred", "Ownership transferred"),
                            ("ownership_canceled", "Ownership canceled"),
                            (
                                "subscription_cancel_requested",
                                "Subscription cancel requested",
                            ),
                            ("subscription_canceled", "Subscription canceled"),
                            (
                                "organization_closure_requested",
                                "Organization closure requested",
                            ),
                            (
                                "organization_closure_canceled",
                                "Organization closure canceled",
                            ),
                            ("organization_closed", "Organization closed"),
                            ("organization_restored", "Organization restored"),
                            (
                                "organization_claim_requested",
                                "Organization claim requested",
                            ),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "event_type", "-created_at"],
                        name="api_organiz_organiz_33442a_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(promote_owners, noop_reverse),
    ]
