# Generated by Django 5.x on 2026-08-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_organization_lifecycle_ownership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessCodeRedemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized access code that was redeemed (uppercase).",
                        max_length=64,
                    ),
                ),
                (
                    "service_level",
                    models.CharField(
                        choices=[
                            ("FREE", "Organization (Free)"),
                            ("BASIC", "Basic"),
                            ("COMMUNITY", "Community"),
                            ("COMMUNITY_PLUS", "Community Plus"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=32,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_code_redemptions",
                        to="api.organization",
                    ),
                ),
                (
                    "organization_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_code_redemptions",
                        to="api.organizationservice",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_code_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="accesscoderedemption",
            index=models.Index(fields=["organization", "code"], name="api_accessc_organiz_7c8f1a_idx"),
        ),
        migrations.AddIndex(
            model_name="accesscoderedemption",
            index=models.Index(fields=["code", "-redeemed_at"], name="api_accessc_code_3e2b91_idx"),
        ),
        migrations.AddConstraint(
            model_name="accesscoderedemption",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"),
                name="uniq_access_code_redemption_per_org_code",
            ),
        ),
    ]
