# Generated by Django 6.0.6 on 2026-08-23 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_access_code_redemption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBoardPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBoardPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='accesscoderedemption',
            new_name='api_accessc_organiz_5e6955_idx',
            old_name='api_accessc_organiz_7c8f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='accesscoderedemption',
            new_name='api_accessc_code_5c5ee8_idx',
            old_name='api_accessc_code_3e2b91_idx',
        ),
        migrations.AddField(
            model_name='boardpost',
            name='event_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='event_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='event_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('question', 'Question'), ('poll', 'Poll'), ('event', 'Event')], default='post', max_length=20),
        ),
        migrations.AddField(
            model_name='personalboardpost',
            name='event_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalboardpost',
            name='event_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personalboardpost',
            name='event_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalboardpost',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('question', 'Question'), ('poll', 'Poll'), ('event', 'Event')], default='post', max_length=20),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organizationauditevent',
            name='event_type',
            field=models.CharField(choices=[('ownership_transferred', 'Ownership transferred'), ('ownership_canceled', 'Ownership canceled'), ('subscription_cancel_requested', 'Subscription cancel requested'), ('subscription_canceled', 'Subscription canceled'), ('paypal_webhook', 'PayPal webhook'), ('organization_closure_requested', 'Organization closure requested'), ('organization_closure_canceled', 'Organization closure canceled'), ('organization_closed', 'Organization closed'), ('organization_restored', 'Organization restored'), ('organization_claim_requested', 'Organization claim requested')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='personalboardpost',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalboardpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='boardpolloption',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='api.boardpost'),
        ),
        migrations.AddField(
            model_name='boardpollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.boardpolloption'),
        ),
        migrations.AddField(
            model_name='boardpollvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='api.boardpost'),
        ),
        migrations.AddField(
            model_name='boardpollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalboardpolloption',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='api.personalboardpost'),
        ),
        migrations.AddField(
            model_name='personalboardpollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.personalboardpolloption'),
        ),
        migrations.AddField(
            model_name='personalboardpollvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='api.personalboardpost'),
        ),
        migrations.AddField(
            model_name='personalboardpollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='boardpollvote',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_board_poll_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='personalboardpollvote',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_personal_poll_vote_per_user'),
        ),
    ]
