# Generated by Django 6.0.8 on 2026-09-20 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_umbrella_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('declared_before_start', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('purpose', 'Purpose'), ('audience', 'Audience / context'), ('topic', 'Topic'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='aiusageevent',
            new_name='api_aiusage_usage_p_2fe4ae_idx',
            old_name='api_aiusage_period_mtg_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationusageperiod',
            new_name='api_organiz_organiz_cfbd3b_idx',
            old_name='api_organiz_organiz_usage_idx',
        ),
        migrations.RenameIndex(
            model_name='surveysubmission',
            new_name='api_surveys_organiz_6a252b_idx',
            old_name='api_surveys_organiz_period_idx',
        ),
        migrations.AddField(
            model_name='meeting',
            name='aggregate_sharing_notice',
            field=models.BooleanField(default=True, help_text='Show participants that anonymous combined results may be shared with policymakers and decision makers not listed on the disclosure screen.'),
        ),
        migrations.AddField(
            model_name='meetingslide',
            name='question_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Normalized hash of prompt/title; groups the same question across meetings.', max_length=40),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Normalized hash of the question text; groups the same question across surveys/meetings.', max_length=40),
        ),
        migrations.AddField(
            model_name='meetingshare',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingshare',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.meeting'),
        ),
        migrations.AddField(
            model_name='meetingshare',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_shared_with_us', to='api.organization'),
        ),
        migrations.AddField(
            model_name='meetingshare',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='api.organization'),
        ),
        migrations.AddField(
            model_name='questiontaglink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiontaglink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tag_links', to='api.organization'),
        ),
        migrations.AddField(
            model_name='questiontaglink',
            name='slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='api.meetingslide'),
        ),
        migrations.AddField(
            model_name='questiontaglink',
            name='survey_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='api.surveyquestion'),
        ),
        migrations.AddField(
            model_name='questiontaglink',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.questiontag'),
        ),
        migrations.AddIndex(
            model_name='meetingshare',
            index=models.Index(fields=['organization', 'status'], name='api_meeting_organiz_f90d05_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingshare',
            constraint=models.UniqueConstraint(fields=('meeting', 'organization'), name='uniq_meeting_share_per_org'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_question_tag_per_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='uniq_global_question_tag_slug'),
        ),
        migrations.AddIndex(
            model_name='questiontaglink',
            index=models.Index(fields=['organization', 'question_key'], name='api_questio_organiz_b7b0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontaglink',
            index=models.Index(fields=['organization', 'tag'], name='api_questio_organiz_fdc0ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontaglink',
            constraint=models.UniqueConstraint(condition=models.Q(('slide__isnull', True), ('survey_question__isnull', True)), fields=('organization', 'tag', 'question_key'), name='uniq_tag_link_org_wide'),
        ),
        migrations.AddConstraint(
            model_name='questiontaglink',
            constraint=models.UniqueConstraint(condition=models.Q(('slide__isnull', False)), fields=('tag', 'slide'), name='uniq_tag_link_slide'),
        ),
        migrations.AddConstraint(
            model_name='questiontaglink',
            constraint=models.UniqueConstraint(condition=models.Q(('survey_question__isnull', False)), fields=('tag', 'survey_question'), name='uniq_tag_link_survey_question'),
        ),
    ]
