"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

APP_ENV = os.getenv("APP_ENV", "local")
env_file = PROJECT_ROOT / f".env.{APP_ENV}"
if env_file.is_file():
    load_dotenv(env_file)
else:
    load_dotenv(PROJECT_ROOT / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bb4i@ge6a^9=hd_neg2yzc%ocj2#d-=hg*m76f9)c8lq*2h9-0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "django.contrib.staticfiles",
    "api.apps.ApiConfig",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_options = {}
if os.getenv("DB_SSLMODE"):
    _db_options["sslmode"] = os.getenv("DB_SSLMODE")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv('DB_PWD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': _db_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWS_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://django-backend-460809694305.us-central1.run.app",
    "https://communib.com",
    "https://www.communib.com",
]

CONTACT_INBOX_EMAIL = os.getenv("CONTACT_INBOX_EMAIL", "contactcommunib@gmail.com")


def _env_or_file(name: str, default: str = "") -> str:
    """Read env var, or contents of {NAME}_FILE (Docker/Secret Manager mount)."""
    value = os.getenv(name)
    if value:
        return value.strip()
    file_path = os.getenv(f"{name}_FILE")
    if file_path and os.path.isfile(file_path):
        with open(file_path, encoding="utf-8") as fh:
            return fh.read().strip()
    return default


if os.getenv("EMAIL_HOST_USER"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
    # Prefer EMAIL_HOST_PASSWORD; GMAIL_KEY is the Secret Manager name used in prod.
    EMAIL_HOST_PASSWORD = _env_or_file("EMAIL_HOST_PASSWORD") or _env_or_file("GMAIL_KEY")
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "communiB <noreply@communib.com>")

# Stage 2+: allow PENDING→ACTIVE simulation without PayPal (never enable casually in production).
BILLING_SIMULATION_ENABLED = os.getenv("BILLING_SIMULATION_ENABLED", "").lower() in (
    "1",
    "true",
    "yes",
)

# PayPal subscriptions (Stage 5+). Secrets via env / Secret Manager only.
# Google Secret Manager names (communib project):
#   PAYPAL_LIVE_CLIENT_ID / PAYPAL_LIVE_SECRET
#   PAYPAL_SANDBOX_CLIENT_ID / PAYPAL_SANDBOX_SECRET
# Cloud Run may map those onto PAYPAL_CLIENT_ID / PAYPAL_CLIENT_SECRET,
# or expose the GSM names directly — both are supported below.
# Local Docker: PAYPAL_*_FILE mounts from secrets/ via pull-paypal-sandbox-local.ps1
PAYPAL_MODE = os.getenv("PAYPAL_MODE", "disabled").strip().lower()  # disabled|sandbox|live
_paypal_client_id = _env_or_file("PAYPAL_CLIENT_ID")
_paypal_client_secret = _env_or_file("PAYPAL_CLIENT_SECRET")
if not _paypal_client_id or not _paypal_client_secret:
    if PAYPAL_MODE == "live":
        _paypal_client_id = _paypal_client_id or _env_or_file("PAYPAL_LIVE_CLIENT_ID")
        _paypal_client_secret = _paypal_client_secret or _env_or_file("PAYPAL_LIVE_SECRET")
    elif PAYPAL_MODE == "sandbox":
        _paypal_client_id = _paypal_client_id or _env_or_file("PAYPAL_SANDBOX_CLIENT_ID")
        _paypal_client_secret = _paypal_client_secret or _env_or_file(
            "PAYPAL_SANDBOX_SECRET"
        )
PAYPAL_CLIENT_ID = _paypal_client_id
PAYPAL_CLIENT_SECRET = _paypal_client_secret
_paypal_webhook_id = _env_or_file("PAYPAL_WEBHOOK_ID")
if not _paypal_webhook_id:
    if PAYPAL_MODE == "live":
        _paypal_webhook_id = _env_or_file("PAYPAL_LIVE_WEBHOOK_ID")
    elif PAYPAL_MODE == "sandbox":
        _paypal_webhook_id = _env_or_file("PAYPAL_SANDBOX_WEBHOOK_ID")
PAYPAL_WEBHOOK_ID = _paypal_webhook_id
PAYPAL_SUBSCRIPTIONS_ENABLED = os.getenv("PAYPAL_SUBSCRIPTIONS_ENABLED", "").lower() in (
    "1",
    "true",
    "yes",
)
# Used for PayPal return/cancel URLs (browser). Local docker: http://localhost:10001
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:10001").rstrip("/")

# Temporary Basic complimentary access code (server-side only; never expose to clients).
# Empty disables access-code redemption. Local Docker sets SUPERBASIC via compose.
COMMUNIB_BASIC_ACCESS_CODE = _env_or_file("COMMUNIB_BASIC_ACCESS_CODE").strip()
